fix: use proper assignment in makefile, enable JS-check in VSCode settings

diff --git a/config/Makefile b/config/Makefile
--- a/config/Makefile
+++ b/config/Makefile
@@ -1,17 +1,19 @@
 .SILENT:
 
+SHELL := /usr/bin/env bash
+
 export PATH := node_modules/.bin:$(PATH)
 
-PKG_NAME = $(shell npm pkg get name | sed -nr 's/^"@(.+)"$$/\1/p')
-GIT_NAME = $(shell git remote get-url origin | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p')
+PKG_NAME := $(shell npm pkg get name 2>/dev/null | sed -nr 's/^"@(.+)"$$/\1/p' 2>/dev/null)
+GIT_NAME := $(shell git remote get-url origin 2>/dev/null | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p' 2>/dev/null)
 
-PKG_VERSION = $(shell npm pkg get version | sed -nr 's/^"(.+)"$$/\1/p')
-GIT_VERSION = $(shell git describe --tag --abbrev=0 | sed -nr 's/^v(.+)$$/\1/p')
+PKG_VERSION := $(shell npm pkg get version 2>/dev/null | sed -nr 's/^"(.+)"$$/\1/p' 2>/dev/null)
+GIT_VERSION := $(shell git describe --tag --abbrev=0 2>/dev/null | sed -nr 's/^v(.+)$$/\1/p' 2>/dev/null)
 
-PKG_REPO_TYPE = $(shell npm pkg get repository.type | sed -nr 's/^"(.+)"$$/\1/p')
-PKG_REPO_NAME = $(shell npm pkg get repository.url | sed -nr 's/^"(.+)"$$/\1/p' | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p')
+PKG_REPO_TYPE := $(shell npm pkg get repository.type 2>/dev/null | sed -nr 's/^"(.+)"$$/\1/p' 2>/dev/null)
+PKG_REPO_NAME := $(shell npm pkg get repository.url 2>/dev/null | sed -nr 's/^"(.+)"$$/\1/p' 2>/dev/null | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p' 2>/dev/null)
 
-ESLINT_ARGS = --ignore-pattern "dist/**/*" --ignore-pattern "node_modules/**/*"
+ESLINT_ARGS := --ignore-pattern "dist/**/*" --ignore-pattern "node_modules/**/*"
 
 check: check_commit check_package_json check_lint check_config check_typescript check_test
 
@@ -27,17 +29,20 @@ check_lint:
 check_package_json: check_package_json_sort check_package_json_repository check_package_json_name check_package_json_version
 
 check_package_json_name:
-	if [ "$(PKG_NAME)" = "$(GIT_NAME)" ]; then exit 0; else echo "name in package.json ($(PKG_NAME)) does not match git repository name ($(GIT_NAME))"; exit 1; fi
+	if [[ -z "$(GIT_NAME)" ]]; then echo "cannot determine git repository name, skipping"; fi
+	if [[ -z "$(GIT_NAME)" || "$(PKG_NAME)" = "$(GIT_NAME)" ]]; then exit 0; else echo "name in package.json ($(PKG_NAME)) does not match git repository name ($(GIT_NAME))"; exit 1; fi
 
 check_package_json_repository:
-	if [ "$(PKG_REPO_TYPE)" = "git" ]; then exit 0; else echo "repository.type in package.json ($(PKG_REPO_TYPE)) does not match \"git\""; exit 1; fi
-	if [ "$(PKG_REPO_NAME)" = "$(GIT_NAME)" ]; then exit 0; else echo "package name derived from repository.url in package.json ($(PKG_REPO_NAME)) does not match git repository name ($(GIT_NAME))"; exit 1; fi
+	if [[ -z "$(GIT_NAME)" ]]; then echo "cannot determine git repository name, skipping"; fi
+	if [[ -z "$(GIT_NAME)" || "$(PKG_REPO_TYPE)" = "git" ]]; then exit 0; else echo "repository.type in package.json ($(PKG_REPO_TYPE)) does not match \"git\""; exit 1; fi
+	if [[ -z "$(GIT_NAME)" || "$(PKG_REPO_NAME)" = "$(GIT_NAME)" ]]; then exit 0; else echo "package name derived from repository.url in package.json ($(PKG_REPO_NAME)) does not match git repository name ($(GIT_NAME))"; exit 1; fi
 
 check_package_json_sort:
 	sort-package-json --check
 
 check_package_json_version:
-	if [ "$(PKG_VERSION)" = "$(GIT_VERSION)" ]; then exit 0; else echo "version in package.json ($(PKG_VERSION)) does not match git repository version ($(GIT_VERSION))"; exit 1; fi
+	if [[ -z "$(GIT_VERSION)" ]]; then echo "cannot determine git repository version, skipping"; fi
+	if [[ -z "$(GIT_VERSION)" || "$(PKG_VERSION)" = "$(GIT_VERSION)" ]]; then exit 0; else echo "version in package.json ($(PKG_VERSION)) does not match git repository version ($(GIT_VERSION))"; exit 1; fi
 
 check_test:
 	jest .
