feat: use makefile recipes for running tasks in sub packages

diff --git a/packages/boilerplate-common/config/Makefile b/packages/boilerplate-common/config/Makefile
--- a/packages/boilerplate-common/config/Makefile
+++ b/packages/boilerplate-common/config/Makefile
@@ -22,6 +22,7 @@
 	transform_prod \
 	transform_typescript \
 	util_clear \
+	util_edit \
 	util_get_version \
 	util_install_git_hooks \
 	watch \
@@ -37,6 +38,32 @@ ARGS := $(filter-out $(firstword $(MAKECMDGOALS)),$(MAKECMDGOALS))
 
 export PATH := $(shell npm root)/.bin:$(PATH)
 
+SUB_PACKAGE_DIR := packages
+
+SUB_RUN = \
+	if [[ "$(include_sub_packages)" = "false" ]]; then \
+		exit 0; \
+	fi; \
+	\
+	if [[ -n "$(sub_package)" ]]; then \
+		exit 0; \
+	fi; \
+	\
+	if [ ! -d "$(SUB_PACKAGE_DIR)" ]; then \
+		exit 0; \
+	fi; \
+	\
+	echo; \
+	\
+	for SUB_PACKAGE in $(SUB_PACKAGE_DIR)/*; do \
+		echo "$$SUB_PACKAGE:$(@)"; \
+		\
+		$(MAKE) "$(@)" sub_package="$$SUB_PACKAGE" -C "$$SUB_PACKAGE" || exit "$$?"; \
+		echo; \
+	done; \
+	\
+	echo "parent:$(@)";
+
 PKG_NAME := $(shell npm pkg get name 2>/dev/null | sed -nr 's/^"@(.+)"$$/\1/p' 2>/dev/null)
 GIT_NAME := $(shell git remote get-url origin 2>/dev/null | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p' 2>/dev/null)
 
@@ -47,7 +74,7 @@ PKG_REPO_TYPE := $(shell npm pkg get repository.type 2>/dev/null | sed -nr 's/^"
 PKG_REPO_NAME := $(shell npm pkg get repository.url 2>/dev/null | sed -nr 's/^"(.+)"$$/\1/p' 2>/dev/null | sed -nr 's/^(https|git)(:\/\/|@)(.+@)?([^\/:]+)[\/:]([^\/:]+)\/(.+)\.git$$/\5\/\6/p' 2>/dev/null)
 PKG_REPO_DIRECTORY := $(shell npm pkg get repository.directory 2>/dev/null | sed -nr 's/^"(.+)"$$/\1/p' 2>/dev/null)
 
-ESLINT_ARGS := --ignore-pattern "dist/**/*" --ignore-pattern "node_modules/**/*" --ignore-pattern "packages/**/*"
+ESLINT_ARGS := --ignore-pattern "dist/**/*" --ignore-pattern "node_modules/**/*" --ignore-pattern "$(SUB_PACKAGE_DIR)/**/*"
 
 %:
 	@:
@@ -76,66 +103,74 @@ check_package_json: \
 	check_package_json_version
 
 check_package_json_name:
+	$(SUB_RUN)
+
 	if [[ -z "$(GIT_NAME)" ]]; then \
 		echo "cannot determine git repository name, skipping"; \
-	fi
-
+		exit 0; \
+	fi; \
+	\
 	if [[ -n "$(PKG_REPO_DIRECTORY)" ]]; then \
 		echo "is sub-package, not comparing to repository name"; \
-	fi
-
-	if [[ -z "$(GIT_NAME)" || -n "$(PKG_REPO_DIRECTORY)" || "$(PKG_NAME)" = "$(GIT_NAME)" ]]; then \
 		exit 0; \
-	else \
+	fi; \
+	\
+	if [[ "$(PKG_NAME)" != "$(GIT_NAME)" ]]; then \
 		echo "name in package.json ($(PKG_NAME)) does not match git repository name ($(GIT_NAME))"; \
 		exit 1; \
-	fi
+	fi;
 
 check_package_json_repository:
+	$(SUB_RUN)
+
 	if [[ -z "$(GIT_NAME)" ]]; then \
 		echo "cannot determine git repository name, skipping"; \
-	fi
-
-	if [[ -z "$(GIT_NAME)" || "$(PKG_REPO_TYPE)" = "git" ]]; then \
 		exit 0; \
-	else \
+	fi;
+	\
+	if [[ "$(PKG_REPO_TYPE)" != "git" ]]; then \
 		echo "repository.type in package.json ($(PKG_REPO_TYPE)) does not match \"git\""; \
 		exit 1; \
-	fi
-
-	if [[ -z "$(GIT_NAME)" || "$(PKG_REPO_NAME)" = "$(GIT_NAME)" ]]; then \
-		exit 0; \
-	else \
+	fi; \
+	\
+	if [[ "$(PKG_REPO_NAME)" != "$(GIT_NAME)" ]]; then \
 		echo "package name derived from repository.url in package.json ($(PKG_REPO_NAME)) does not match git repository name ($(GIT_NAME))"; \
 		exit 1; \
-	fi
-
-	if [[ -z "$(ARGS)" || "$(PKG_REPO_DIRECTORY)" = "$(ARGS)" ]]; then \
+	fi; \
+	\
+	if [[ -z "$(sub_package)" ]]; then \
 		exit 0; \
-	else \
-		echo "sub-package directory derived from repository.directory in package.json ($(PKG_REPO_DIRECTORY)) does not match required directory ($(ARGS))"; \
+	fi; \
+	\
+	if [[ "$(PKG_REPO_DIRECTORY)" != "$(sub_package)" ]]; then \
+		echo "sub-package directory derived from repository.directory in package.json ($(PKG_REPO_DIRECTORY)) does not match required directory ($(sub_package))"; \
 		exit 1; \
-	fi
+	fi;
 
 check_package_json_sort:
+	$(SUB_RUN)
+
 	sort-package-json --check
 
 check_package_json_version:
 	if [[ -z "$(GIT_VERSION)" ]]; then \
 		echo "cannot determine git repository version, skipping"; \
-	fi
-
-	if [[ -z "$(GIT_VERSION)" || "$(PKG_VERSION)" = "$(GIT_VERSION)" ]]; then \
 		exit 0; \
-	else \
+	fi; \
+	\
+	if [[ "$(PKG_VERSION)" != "$(GIT_VERSION)" ]]; then \
 		echo "version in package.json ($(PKG_VERSION)) does not match git repository version ($(GIT_VERSION))"; \
 		exit 1; \
-	fi
+	fi;
 
 check_test:
+	$(SUB_RUN)
+
 	jest .
 
 check_typescript:
+	$(SUB_RUN)
+
 	tsc
 
 transform: \
@@ -148,6 +183,8 @@ transform_clear: \
 	transform
 
 transform_lint:
+	$(SUB_RUN)
+
 	eslint --fix $(ESLINT_ARGS) .
 
 transform_package_json: \
@@ -156,6 +193,8 @@ transform_package_json: \
 	transform_package_json_version
 
 transform_package_json_name:
+	$(SUB_RUN)
+
 	if [[ -n "$(PKG_REPO_DIRECTORY)" ]]; then \
 		echo "is sub-package, not applying repository name"; \
 	else \
@@ -163,9 +202,13 @@ transform_package_json_name:
 	fi
 
 transform_package_json_sort:
+	$(SUB_RUN)
+
 	sort-package-json
 
 transform_package_json_version:
+	$(SUB_RUN)
+
 	npm pkg set "version=$(GIT_VERSION)"
 
 transform_prod: \
@@ -173,10 +216,19 @@ transform_prod: \
 	transform_typescript
 
 transform_typescript:
+	$(SUB_RUN)
+
 	tsc --project tsconfig.build.json
 
 util_clear:
+	$(SUB_RUN)
+
 	rm -rf dist/{*,.*}
+
+util_edit:
+	$(SUB_RUN)
+
+	code .
 
 util_get_version:
 	@echo $(PKG_VERSION)
@@ -195,7 +247,7 @@ watch_dev:
 
 watch_lint:
 	chokidar --initial "**/*.js" "src/**/*.{js,ts}" --ignore "dist/**/*" --ignore "node_modules/**/*" --ignore "*.d.ts" \
-		--command "clear; eslint --ignore-pattern \"dist/**/*\" --ignore-pattern \"node_modules/**/*\" --ignore-pattern \"packages/**/*\" .; echo \"[waiting for changes…]\""
+		--command "clear; eslint --ignore-pattern \"dist/**/*\" --ignore-pattern \"node_modules/**/*\" --ignore-pattern \"$(SUB_PACKAGE_DIR)/**/*\" .; echo \"[waiting for changes…]\""
 
 watch_test:
 	jest --watch .
